export const PAGE_TITLE = "PAGE_TITLE";


// Header


export const MSG_BOX = "MSG_BOX";
export const SEND_MSG = "SEND_MSG";
export const ADD_USER = "ADD_USER";
export const SEARCH_DATA = "SEARCH_DATA";
export const NOTES = "NOTES";
export const ADD_NOTE = "ADD_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";

// demo
export const DEMO = "DEMO";

// setting
export const TYPOGRAPHY = "TYPOGRAPHY";
export const VERSION = "VERSION";
export const LAYOUT = "LAYOUT";
export const PRIMARY = "PRIMARY";
export const HEADER_BG = "HEADER_BG";
export const NAV_HEADER_BG = "NAV_HEADER_BG";
export const SIDEBAR_BG = "SIDEBAR_BG";
export const SIDEBAR_STYLE = "SIDEBAR_STYLE";
export const SIDEBAR_POSITION = "SIDEBAR_POSITION";
export const HEADER_POSITION = "HEADER_POSITION";
export const CONTAINER_LAYOUT = "CONTAINER_LAYOUT";
export const DIRACTION = "DIRACTION";

// Pages
// Index Page
export const DAILY_TARGET_CHART = "DAILY_TARGET_CHART";
export const ORDER_CHART = "ORDER_CHART";
export const CUSTOMER_CHART = "CUSTOMER_CHART";
export const ADD_CUSTOMER_LIST = "ADD_CUSTOMER_LIST";
export const MENU_CHART = "MENU_CHART";
export const CUSTOMER_MAP_CHART = "CUSTOMER_MAP_CHART";
export const ORDER_REQUEST = "ORDER_REQUEST";
export const TRANDING_MENU = "TRANDING_MENU";
export const ORDER_DETAILS_ITEMS = "ORDER_DETAILS_ITEMS";
export const DELETE_ORDER_DETAILS = "DELETE_ORDER_DETAILS";

// Order list
export const ORDERS_LIST = "ORDERS_LIST";

// Order Detail
export const ORDER_DETAILS = "ORDER_DETAILS";

// Customer List
export const CUSTOMER_LIST = "CUSTOMER_LIST";

// analytics
export const ANALYTICS = "ANALYTICS";

// Reviews
export const REVIEWS = "REVIEWS";

// Apps
// profile
export const PROFILE = "PROFILE";

// Posts
export const POSTS = "POSTS";
export const GET_POSTS = "GET_POSTS";
export const DELETE_POST = "DELETE_POST";
export const EDIT_POST = "EDIT_POST";

// HeaderImg
export const HEADER_IMG = "HEADER_IMG";

// interest
export const INTEREST = "INTEREST";

// Email
export const EMAIL_READ = "EMAIL_READ";

// Email inbox
export const EMAIL_INBOX = "EMAIL_INBOX";

// Product
// -> Grid
export const PRODUCTS = "PRODUCTS";
// -> Order
export const PRODUCTS_ORDER = "PRODUCTS_ORDER";
// -> Invoice
export const INVOICE = "INVOICE";
export const EDIT_INVOICE = "EDIT_INVOICE";
export const INVOICE_ITEMS = "INVOICE_ITEMS";
export const INVOICE_ITEMS_EDIT = "INVOICE_ITEMS_EDIT";
export const INVOICE_ITEMS_DELETE = "INVOICE_ITEMS_DELETE";
export const ADD_INVOICE_ITEMS = "ADD_INVOICE_ITEMS";
export const DELETE_INVOICE = "DELETE_INVOICE";
// -> Customer list
export const APP_CUSTOMER_LIST = "APP_CUSTOMER_LIST";

// Widget page
export const WIDGET_BASIC = "WIDGET_BASIC";

// Auth
export const GET_USER = "GET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTH_ERROR = "AUTH_ERROR";


// Table
export const BASIC_TABLE = "BASIC_TABLE";
export const PROFILE_TABLE = "PROFILE_TABLE";
export const FEE_TABLE = "FEE_TABLE";
export const PATIENT_TABLE = "PATIENT_TABLE";
export const DELETE_PROFILE_TABLE = "DELETE_PROFILE_TABLE";
export const EDIT_PROFILE_TABLE = "EDIT_PROFILE_TABLE";

// Table -> bs
export const GET_BS_TABLE = "BS_TABLE";
export const RECENT_PAYMENT_QUEUE = "RECENT_PAYMENT_QUEUE";
export const DELETE_RECENT_PAYMENT_QUEUE = "DELETE_RECENT_PAYMENT_QUEUE";
export const EDIT_RECENT_PAYMENT_QUEUE = "EDIT_RECENT_PAYMENT_QUEUE";
export const EDIT_EXAM_TOPPERS = "EDIT_EXAM_TOPPERS";
export const DELETE_EXAM_TOPPERS = "DELETE_EXAM_TOPPERS";
export const EXAM_TOPPERS = "EXAM_TOPPERS";
export const BORDER_TABLE = "BORDER_TABLE";
export const EDIT_BORDER_TABLE = "EDIT_BORDER_TABLE";
export const DELETE_BORDER_TABLE = "DELETE_BORDER_TABLE";
export const TABLE_STRIPPED = "TABLE_STRIPPED";
export const EDIT_TABLE_STRIPPED = "EDIT_TABLE_STRIPPED";
export const DELETE_TABLE_STRIPPED = "DELETE_TABLE_STRIPPED";




//GENERAL
/*NOTIFICATIONS*/
export const NOTIFIACIONS_SUCCESS = 'NOTIFIACIONS_SUCCESS'
export const NOTIFICATIONS_FAILURE = 'NOTIFICATIONS_FAILURE'
export const NOTIFICATION_RESET = 'NOTIFICATION_RESET'

/*LOADING*/
export const LOADING_ACTIVATE = 'LOADING_ACTIVATE'
export const LOADING_DEACTIVATE = 'LOADING_DEACTIVATE'

/*FINCA*/
export const LOAD_FINCA_SUCCESS = 'LOAD_FINCA_SUCCESS'
export const LOAD_FINCA_FAILURE = 'LOAD_FINCA_FAILURE'

export const FINCA_SUCCESS = 'FINCA_SUCCESS'
export const FINCA_FAILURE = 'FINCA_FAILURE'
export const FINCA_DEACTIVATE = 'FINCA_DEACTIVATE'

/*Area*/
export const LOAD_AREA_SUCCESS ='LOAD_AREA_SUCCESS'
export const LOAD_AREA_FAILURE = 'LOAD_AREA_FAILURE'
export const AREA_SUCESS = 'AREA_SUCESS'
export const AREA_FAILURE = 'AREA_FAILURE'
export const AREA_DEACTIVATE = 'AREA_DEACTIVATE'

/*Pilon*/
export const LOAD_PILON_SUCCESS = 'LOAD_PILON_SUCCESS'
export const LOAD_PILON_FAILURE = 'LOAD_PILON_FAILURE'
export const PILON_SUCCESS = 'PILON_SUCCESS'
export const PILON_FAILURE ='PILON_FAILURE'
export const PILON_DEACTIVATE ='PILON_DEACTIVATE'

/*Clases*/
export const LOAD_CLASES_SUCCESS = 'LOAD_CLASES_SUCCESS'
export const LOAD_CLASES_FAILURE = 'LOAD_CLASES_FAILURE'
export const CLASE_SUCCESS = 'CLASE_SUCCESS'
export const CLASE_FAILURE = 'CLASE_FAILURE'
export const CLASE_DEACTIVATE ='CLASE_DEACTIVATE'

/*Corte*/
export const LOAD_CORTE_SUCCESS = 'LOAD_CORTE_SUCCESS'
export const LOAD_CORTE_FAILURE = 'LOAD_CORTE_FAILURE'
export const CORTE_SUCCESS = 'CORTE_SUCCESS'
export const CORTE_FAILURE = 'CORTE_FAILURE'
export const CORTE_DEACTIVATE = 'CORTE_DEACTIVATE'

/*Variedad*/
export const LOAD_VARIEDAD_SUCCESS ='LOAD_VARIEDAD_SUCCESS'
export const LOAD_VARIEDAD_FAILURE = 'LOAD_VARIEDAD_FAILURE'
export const VARIEDAD_SUCESS ='VARIEDAD_SUCESS'
export const VARIEDAD_FAILURE = 'VARIEDAD_FAILURE'
export const VARIEDAD_DEACTIVATE = 'VARIEDAD_DEACTIVATE'

/*Login*/
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL'

export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'

export const LOAD_ACCESS_SUCCESS = 'LOAD_ACCESS_SUCCESS'
export const LOAD_ACCESS_FAIL = 'LOAD_ACCESS_FAIL'

/*Bultos*/
export const LOAD_BULTOS_SUCCESS ='LOAD_BULTOS_SUCCESS'
export const LOAD_BULTOS_FAIL = 'LOAD_BULTOS_FAIL'
export const ACTION_BULTOS_SUCCESS = 'ACTION_BULTOS_SUCCESS'
export const ACTION_BULTOS_FAIL = 'ACTION_BULTOS_FAIL'
export const BULTO_DEACTIVATE = 'BULTO_DEACTIVATE'

/*Update State*/
export const SET_UPDATE = 'SET_UPDATE'
export const SET_DEFAULT = 'SET_DEFAULT'


/*MOVIES STATES*/
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS'
export const LOAD_MOVIES_FAIL = 'LOAD_MOVIES_FAIL'
export const ACTION_MOVIES_SUCCESS = 'ACTION_MOVIES_SUCCESS'
export const ACTION_MOVIES_FAIL = 'ACTION_MOVIES_FAIL'
export const MOVIE_DEACTIVATE = 'MOVIE_DEACTIVATE'

/*Movies by Date*/
export const LOAD_MOVIES_BYDATE_SUCCESS = 'LOAD_MOVIES_BYDATE_SUCCESS'
export const LOAD_MOVIES_BYDATE_FAIL = 'LOAD_MOVIES_BYDATE_FAIL'
export const ACTION_MOVIES_BYDATE_SUCCESS = 'ACTION_MOVIES_BYDATE_SUCCESS'
export const ACTION_MOVIES_BYDATE_FAIL = 'ACTION_MOVIES_BYDATE_FAIL'
export const MOVIE_BYDATE_DEACTIVATE = 'MOVIE_BYDATE_DEACTIVATE'

/*Movies top Rating*/
export const LOAD_MOVIES_TOP_SUCCESS = 'LOAD_MOVIES_TOP_SUCCESS'
export const LOAD_MOVIES_TOP_FAIL = 'LOAD_MOVIES_TOP_FAIL'
export const ACTION_MOVIES_TOP_SUCCESS = 'ACTION_MOVIES_TOP_SUCCESS'
export const ACTION_MOVIES_TOP_FAIL = 'ACTION_MOVIES_TOP_FAIL'
export const MOVIE_TOP_DEACTIVATE = 'MOVIE_TOP_DEACTIVATE'

/*Comments*/
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'
export const LOAD_COMMENTS_FAIL = 'LOAD_COMMENTS_FAIL'
export const ACTION_COMMENTS_SUCCESS = 'ACTION_COMMENTS_SUCCESS'
export const ACTION_COMMENTS_FAIL = 'ACTION_COMMENTS_FAIL'
export const ACTION_COMMENTS_DEACTIVATE = 'ACTION_COMMENTS_DEACTIVATE'

/*Admin User*/
export const LOAD_USERS_DATA_SUCCESS = 'LOAD_USERS_DATA_SUCCESS'
export const LOAD_USERS_DATA_FAIL = 'LOAD_USERS_DATA_FAIL'
export const ACTION_USERS_SUCCESS = 'ACTION_USERS_SUCCESS'
export const ACTION_USERS_FAIL = 'ACTION_USERS_FAIL'
export const ACTION_USERS_DEACTIVATE = 'ACTION_USERS_DEACTIVATE'


/*Movies Finded*/
export const LOAD_MOVIES_FINDED = 'LOAD_MOVIES_FINDED'
export const LOAD_MOVIES_FINDED_FAIL = 'LOAD_MOVIES_FINDED_FAIL'
export const ACTION_MOVIES_FINDED_SUCCESS = 'ACTION_MOVIES_FINDED_SUCCESS'
export const ACTION_MOVIES_FINDED_FAIL = 'ACTION_MOVIES_FINDED_FAIL'
export const MOVIE_FINDED_DEACTIVATE = 'MOVIE_FINDED_DEACTIVATE'


/*Movies Admin*/
export const LOAD_MOVIES_ADMIN_SUCCESS = 'LOAD_MOVIES_ADMIN_SUCCESS'
export const LOAD_MOVIES_ADMIN_FAIL = 'LOAD_MOVIES_ADMIN_FAIL'
export const ACTION_MOVIES_ADMIN_SUCCESS = 'ACTION_MOVIES_ADMIN_SUCCESS'
export const ACTION_MOVIES_ADMIN_FAIL = 'ACTION_MOVIES_ADMIN_FAIL'
export const ACTION_MOVIES_ADMIN_DEACTIVATE = 'ACTION_MOVIES_ADMIN_DEACTIVATE'

/*Genres Administration*/
export const LOAD_GENRES_SUCCESS = 'LOAD_GENRES_SUCCESS'
export const LOAD_GENRES_FAIL = 'LOAD_GENRES_FAIL'
export const ACTION_GENRES_SUCCESS = 'ACTION_GENRES_SUCCESS'
export const ACTION_GENRES_FAIL = 'ACTION_GENRES_SUCCESS'
export const ACTION_GENRES_DEACTIVATE = 'ACTION_GENRES_DEACTIVATE'